replicaCount: 1

image:
  repository: adeeshadev/analytics-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5003

clickhouse:
  host: clickhouse-server
  db: analytics
  user: analytics_user
  password: test123
  port: 9000